<?php
$title = "系統說明";
require("layout/header.php");
?>

<br>
<ol>
    <li>宿舍 & 房間</li>
    <ul>
        <li>建立大樓、設備</li>
        <li>建立房間、設備</li>
    </ul>
    <br>
    <li>註冊人員</li>
    <ul>
        <li>系統管理員</li>
        <li>學生</li>
    </ul>
    <br>
    <li>學生</li>
    <ul>
       <li>修改密碼</li>
       <li>申請宿舍</li>
    </ul>
    <br>
    <li>管理員</li>
    <ul>
        <li>核可申請、分配房間</li>
        <li>發布公告</li>
        <li>新增舍監</li>
    </ul>
    <br>
    <li>學生</li>
    <ul>
       <li>繳費</li>
       <li>留言</li>
    </ul>
    <br>
    <li>舍監</li>
    <ul>
       <li>回覆留言</li>
       <li>登記違規</li>
    </ul>
</ol>